use HotelBooking

DROP TABLE IF EXISTS Quantities;
DROP TABLE IF EXISTS Prices;
DROP TABLE IF EXISTS ExtraServices;
DROP TABLE IF EXISTS ReservationsLines;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS RoomTypes;
DROP TABLE IF EXISTS Reservations;
DROP TABLE IF EXISTS Persons;
DROP TABLE IF EXISTS PersonAddress;
DROP TABLE IF EXISTS PersonTypes;